# Generated by Django 4.2 on 2023-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_admin_kitob_muallif_talaba_record_kitob_muallif_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='ism',
            field=models.CharField(max_length=50),
        ),
    ]
