# Generated by Django 4.2 on 2023-04-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_muallif_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='ish_vaqti',
            field=models.CharField(max_length=100),
        ),
    ]
